baseurl = "/"
title = "AgroClubRSE"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "L'AgroClubRSE, communauté agro engagée."
  copyright = "&copy;2019 AgroClubRSE - Gestion: Julien Mottet"
  sidebarAbout = [
    "#AgroClubRSE #Communauté #Agroalimentaire #RSE #Hauts-de-France ."  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "j.mottet@agroe.fr"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Miscellaneous"
  url = "agroclubrse-post/"
  home = true

  [[params.navlinks]]
  name = "Edito"
  url = "edito/"

  [[params.navlinks]]
  name = "Contact"
  url = "contactez-nous/"

  [params.social]
  email         = "j.mottet@agroe.fr"
  linkedin      = "https://www.linkedin.com/company/18518876/admin/"
  youtube       = "https://www.youtube.com/channel/UCinUo8-stq3edw4Ozo2qRAg/videos"
  facebook      = "https://www.facebook.com/poleagroe/"
